poll_system.settings:
  type: config_object
  label: 'Poll System settings'
  mapping:
    voting_enabled:
      type: boolean
      label: 'Enable voting'
    show_totals_default:
      type: boolean
      label: 'Default show totals'
    api_key:
      type: string
      label: 'API key'
